### ISSUE TITLE
MIS error? or merging error?

### ISSUE THREAD

**Issue by tigrazone** [ciechowoj/master#1]
Hello!
Is an error is MIS calculation or it is merging error on image from front page of repo?
UPG image
![image](https://raw.githubusercontent.com/ciechowoj/master/master/images/Bearings.UPG.0_1.1797s.png)
BPT image
![image](https://raw.githubusercontent.com/ciechowoj/master/master/images/Bearings.BPT.1790s.png)
I speak about these spots
![image](https://user-images.githubusercontent.com/3808839/209319780-dfb2221a-a739-46cd-b121-277753d81956.png)

How to fix it?

**Comment by ciechowoj** [comment]
It's not an error, it's just the same phenomenon that causes artifacts on BPT, in case of UPG it affects multiple pixels as the path is connected with multiple 'photons' in the area.

It can only be fixed by more samples... I suspect they don't have those problems in pictures from the UPG paper as they show results from UPB + BPT hybrid and in my case it's just UPG alone.

I think this is mentioned here:

> Other Sampling Strategies combine Photon Mapping with Bidirectional Path Tracing to reproduce even more complex light
paths. Two equivalent methods, Vertex Connection and Merging
(VCM) [GKDS12] and Unified Path Sampling (UPS) [HPJ12],
were found independently at the same time. **However, VCM/UPS
and SPPM do not recover from early iterations’ artifacts in practice.** Unbiased Photon Gathering (UPG) [QSH∗15] improves upon
the gathering event by computing probabilities more carefully. To
the best of our knowledge this is the most qualitative general GI
method, but it requires a variable count of trial rays per connection
event, which is not suitable for GPU implementations.

In "Pixel Cache Light Tracing"
